name: Mon premier Workflow
on: workflow_dispatch
jobs:
  premierJob:
    runs-on: ubuntu-latest
    steps:
      - name: Mon Premier Job
        run: echo "DÃ©marrage du Job"
      - name: Mes premieres instructions
        run: ls /
      - name: Fin du premier Job
        run: echo "That's all for folks"
